//
// Copyright (c) ZeroC, Inc. All rights reserved.
//
//
// Ice version 3.7.10
//
// <auto-generated>
//
// Generated from file `App.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package Demo;

public final class PrinterI implements Printer
{
    public PrinterI()
    {
    }

    @Override
    public void printString(String s, com.zeroc.Ice.Current current)
    {
	System.out.println(s + "  Hola desde el Worker");
    }
}
